
api:
  pattern: /api/{o=int,call:Test\Api@,object}/{o2=int,call:Test\Api@,object|o2=call:Test\Api@(8)}
  # call: o@getId
  api:
    id1:
      type: int
      get: o@getId
    id2:
      type: string
      get: o@getOther(o2, 34, 2)
    integer:
      type: int|null
      min: 1
      max: 9000
      get: o@getInteger
      # format: '%6d'
    type:
      type: string|null
      get: o@getType
      set: o@setType
      required:
        create: false
        update: true
      accept:
        - electrical
        - oil
        - gas
    time:
      type: datetime
      timezone: '+0000'
      format: Y-H:i:s
      get: o@getTime
    xxx:
      type: string
      required: false
